### ISSUE TITLE
USER option not working

### ISSUE THREAD

**Issue by Roucou** [microsoft/openjdk-docker#47]
Running this image as non-root fails, i.e. the Docker compose file below doesn't run the container as user 1001 and group 1001, as it should.

```
version: "3"
services:
  minecraft:
    image: mcr.microsoft.com/openjdk/jdk:17-distroless
    container_name: minecraft
    ports:
      - 25565:25565/tcp
    restart: unless-stopped
    volumes:
      - /opt/minecraft:/opt/minecraft
    command: ["-Xms8G", "-Xmx8G", "-jar", "/opt/minecraft/minecraft-server.jar", "nogui"]
    user: 1001:1001
```
